version: '3.7'

services:
  dplm:
    env_file:
      - web.env
    restart: unless-stopped
    command: gunicorn dplmhub.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    build:
      context: ./dplmhub_root

