# Generated by Django 4.0.1 on 2022-01-13 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Page',
        ),
    ]
