# Generated by Django 4.0.1 on 2022-01-18 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devs', '0003_remove_device_uid_device_clientid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='device',
            name='wifi_ssid',
            field=models.CharField(default='DPLM_BaseNetwork', max_length=100),
        ),
        migrations.AlterField(
            model_name='device',
            name='clientID',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
