# Generated by Django 4.0.1 on 2022-01-29 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0001_initial'),
        ('devs', '0004_device_last_update_device_wifi_ssid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Controller',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='devs.device')),
                ('modelName', models.CharField(default='', max_length=100)),
            ],
            bases=('devs.device',),
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='devs.device')),
                ('frequency', models.PositiveIntegerField()),
            ],
            bases=('devs.device',),
        ),
        migrations.AlterField(
            model_name='device',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='userAuth.devicemaster'),
        ),
        migrations.CreateModel(
            name='Grid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker_name', models.CharField(default='Default Broker', max_length=100)),
                ('wifi_ssid', models.CharField(default='DPLM_BaseNetwork', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='userAuth.devicemaster')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='grid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='devs.grid'),
        ),
    ]
