# Generated by Django 4.0.1 on 2022-01-30 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devs', '0005_controller_sensor_alter_device_user_grid_device_grid'),
    ]

    operations = [
        migrations.AddField(
            model_name='grid',
            name='broker_adress',
            field=models.CharField(default='', max_length=40),
        ),
    ]
